const {test}=require('node:test');const assert=require('node:assert/strict');const {evaluate,toCSV}=require('../scoring.js');
const quotes=[{name:'Cheap',price:100,delivery:20,quality:80},{name:'Fast',price:125,delivery:5,quality:95}];
test('weighted scores and ranking',()=>{const e=evaluate(quotes,{price:50,delivery:30,quality:20});assert.equal(e.result[0].name,'Fast');assert.equal(e.result[0].score,89);assert.equal(e.result[1].score,73.5);});
test('deadline excludes highest scoring late supplier',()=>{const e=evaluate(quotes,{price:100,delivery:0,quality:0},10);assert.equal(e.result[0].name,'Fast');assert.equal(e.result[1].eligible,false);});
test('all late quotes remain visible and ineligible',()=>assert.ok(evaluate(quotes,{price:1,delivery:1,quality:1},2).result.every(q=>!q.eligible)));
test('ties share ranks',()=>{const e=evaluate([quotes[0],{...quotes[0],name:'Other'}],{price:50,delivery:30,quality:20});assert.deepEqual(e.result.map(q=>q.rank),[1,1]);});
test('weights are normalized',()=>assert.equal(evaluate(quotes,{price:10,delivery:0,quality:0}).result[0].score,100));
test('reject unsafe and incomplete inputs',()=>{for(const price of [0,-1,NaN,Infinity])assert.throws(()=>evaluate([{...quotes[0],price},quotes[1]],{price:1,delivery:1,quality:1}));assert.throws(()=>evaluate(quotes,{price:0,delivery:0,quality:0}));assert.throws(()=>evaluate(quotes,{price:1,delivery:1,quality:1},0));assert.throws(()=>evaluate([quotes[0],{...quotes[1],name:' cheap '}],{price:1,delivery:1,quality:1}));assert.throws(()=>evaluate([{...quotes[0],quality:101},quotes[1]],{price:1,delivery:1,quality:1}));});
test('CSV escapes formulas, quotes and preserves settings',()=>{const e=evaluate([{...quotes[0],name:'=SUM(1,2)'},{...quotes[1],name:'A "quoted" name'}],{price:50,delivery:30,quality:20},10);const csv=toCSV(e,'LKR');assert.ok(csv.includes('"\'=SUM(1,2)"'));assert.ok(csv.includes('A ""quoted"" name'));assert.ok(csv.includes('Price weight %'));assert.ok(csv.includes('"10"'));});
